from gym_touchhand.envs.touchtest_env import HandBlockTouchSensorsTestEnv
from gym_touchhand.envs.touchtest_env import HandEggTouchSensorsTestEnv
from gym_touchhand.envs.touchtest_env import HandPenTouchSensorsTestEnv
